"""Kairos Research Dashboard.

Run with::

    streamlit run dashboard/app.py
"""

from __future__ import annotations

import streamlit as st

st.set_page_config(
    page_title="Kairos Research Dashboard",
    page_icon="🔬",
    layout="wide",
    initial_sidebar_state="expanded",
)


def main() -> None:
    st.sidebar.title("🔬 Kairos")

    st.sidebar.markdown("---")
    st.sidebar.markdown("### Navigation")

    pages = {
        "Experiments": "experiments",
        "Benchmarks": "benchmarks",
        "Ablations": "ablations",
        "Statistics": "statistics",
        "Observability": "observability",
    }

    for label, page in pages.items():
        if st.sidebar.button(label, use_container_width=True):
            st.switch_page(f"pages/{page}.py")

    st.sidebar.markdown("---")
    st.sidebar.markdown("### System Info")
    st.sidebar.markdown("**Status:** Dashboard Ready")
    st.sidebar.markdown("**Version:** Phase 7")

    st.title("🔬 Kairos Research Dashboard")
    st.markdown(
        """
        Welcome to the Kairos Research Dashboard.

        Use the sidebar to navigate between sections:

        - **Experiments** — Browse experiment runs, metrics, rankings
        - **Benchmarks** — Explore dataset performance and trends
        - **Ablations** — Analyze feature contributions and deltas
        - **Statistics** — View p-values, confidence intervals, effect sizes
        - **Observability** — Monitor latency, failures, alerts, throughput

        ---
        *Dashboard generated by the Kairos research reporting framework.*
        """
    )


if __name__ == "__main__":
    main()
