import { prisma } from "@/lib/prisma";
import { logger } from "@/lib/logger";

const DEMO_USER_EMAIL = "demo@kairos.dev";
const DEMO_USER_NAME = "Demo User";

let cachedUserId: string | null = null;

/**
 * Demo identity email. Normally the shared demo user; integration tests that
 * depend on deterministic org selection (selection falls back to the user's
 * first organization) can set KAIROS_DEMO_USER_ID so each test file gets its
 * own user instead of sharing the multi-org demo account. Non-demo code never
 * sets it.
 */
function demoUserEmail(): string {
  const id = process.env.KAIROS_DEMO_USER_ID;
  if (id) {
    const slug = id.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 48) || "demo";
    return `demo-${slug}@kairos.dev`;
  }
  return DEMO_USER_EMAIL;
}

export interface DemoSession {
  user: {
    id: string;
    email: string;
    name: string;
    role: string;
    image?: string | null;
  };
}

/**
 * Returns true only if demo mode is explicitly enabled via KAIROS_DEMO_MODE=true.
 * Demo mode is NEVER active in production: every anonymous request would
 * otherwise be treated as the demo ADMIN user, silently bypassing auth.
 */
export function isDemoModeEnabled(): boolean {
  if (process.env.NODE_ENV === "production") return false;
  return process.env.KAIROS_DEMO_MODE === "true";
}

/**
 * Ensures the demo user exists in the database. Uses `email` (a unique field)
 * as the upsert key instead of `id` (which is auto-generated by cuid).
 * Only call this from API routes / server actions — never during rendering.
 */
export async function ensureDemoUser(): Promise<string> {
  if (!isDemoModeEnabled()) {
    throw new Error("Demo mode is not enabled. Set KAIROS_DEMO_MODE=true to enable.");
  }

  if (cachedUserId) return cachedUserId;

  try {
    const user = await prisma.user.upsert({
      where: { email: demoUserEmail() },
      update: {},
      create: {
        email: demoUserEmail(),
        name: DEMO_USER_NAME,
        emailVerified: true,
      },
      select: { id: true },
    });

    cachedUserId = user.id;
    return user.id;
  } catch (err) {
    logger.error("ensureDemoUser failed", { error: err instanceof Error ? err.message : String(err) });
    throw new Error("Failed to initialize demo user. Check that the database is available.", { cause: err });
  }
}

/**
 * Read-only lookup for the demo user ID. Returns null if the user does not
 * exist yet (e.g. before the seed script has run) or if the database is
 * unreachable (e.g. during build without a live DB). Safe to call during
 * rendering / build-time.
 */
export async function getDemoUserId(): Promise<string | null> {
  if (!isDemoModeEnabled()) return null;

  if (cachedUserId) return cachedUserId;

  try {
    const user = await prisma.user.findUnique({
      where: { email: demoUserEmail() },
      select: { id: true },
    });

    if (!user) return null;
    cachedUserId = user.id;
    return user.id;
  } catch {
    return null;
  }
}

/**
 * Returns a session object for the demo user. Only works when demo mode is
 * explicitly enabled. Falls back to null session in non-demo mode.
 */
export async function getDemoSession(): Promise<DemoSession | null> {
  if (!isDemoModeEnabled()) return null;

  const userId = await getDemoUserId();
  return {
    user: {
      id: userId ?? "",
      email: demoUserEmail(),
      name: DEMO_USER_NAME,
      role: "ADMIN",
      image: null,
    },
  };
}
