import { prisma } from "@/lib/prisma";

const DEMO_USER_EMAIL = "demo@kairos.dev";
const DEMO_USER_NAME = "Demo User";

let cachedUserId: string | null = null;
let cachedOrgId: string | null = null;
let cachedProjectId: string | null = null;

export interface DemoSession {
  user: {
    id: string;
    email: string;
    name: string;
    role: string;
  };
}

/**
 * Ensures the demo user exists in the database. Uses `email` (a unique field)
 * as the upsert key instead of `id` (which is auto-generated by cuid).
 * Only call this from API routes / server actions — never during rendering.
 */
export async function ensureDemoUser(): Promise<string> {
  if (cachedUserId) return cachedUserId;

  const user = await prisma.user.upsert({
    where: { email: DEMO_USER_EMAIL },
    update: {},
    create: {
      email: DEMO_USER_EMAIL,
      name: DEMO_USER_NAME,
      emailVerified: true,
    },
    select: { id: true },
  });

  cachedUserId = user.id;
  return user.id;
}

/**
 * Read-only lookup for the demo user ID. Returns null if the user does not
 * exist yet (e.g. before the seed script has run) or if the database is
 * unreachable (e.g. during build without a live DB). Safe to call during
 * rendering / build-time.
 */
export async function getDemoUserId(): Promise<string | null> {
  if (cachedUserId) return cachedUserId;

  try {
    const user = await prisma.user.findUnique({
      where: { email: DEMO_USER_EMAIL },
      select: { id: true },
    });

    if (!user) return null;
    cachedUserId = user.id;
    return user.id;
  } catch {
    return null;
  }
}

/**
 * Read-only lookup for the demo org and project. Returns null when the
 * demo data has not been seeded yet. Never creates any records.
 */
export async function getDemoOrgAndProject(): Promise<{
  orgId: string;
  projectId: string;
} | null> {
  if (cachedOrgId && cachedProjectId) {
    return { orgId: cachedOrgId, projectId: cachedProjectId };
  }

  try {
    const userId = await getDemoUserId();
    if (!userId) return null;

    const existing = await prisma.member.findFirst({
      where: { userId },
      select: { organizationId: true },
    });

    if (!existing) return null;

    const orgWithProjects = await prisma.organization.findUnique({
      where: { id: existing.organizationId },
      select: {
        id: true,
        projects: { select: { id: true }, take: 1 },
      },
    });

    if (!orgWithProjects || orgWithProjects.projects.length === 0) return null;

    cachedOrgId = orgWithProjects.id;
    cachedProjectId = orgWithProjects.projects[0].id;
    return { orgId: orgWithProjects.id, projectId: orgWithProjects.projects[0].id };
  } catch {
    return null;
  }
}

/**
 * Returns a session object for the demo user. Reads the user ID from the
 * database when possible; falls back to a placeholder only for display
 * purposes when no seed data exists yet.
 */
export async function getDemoSession(): Promise<DemoSession> {
  const userId = await getDemoUserId();
  return {
    user: {
      id: userId ?? "",
      email: DEMO_USER_EMAIL,
      name: DEMO_USER_NAME,
      role: "ADMIN",
    },
  };
}
