from __future__ import annotations

import html as html_mod
from typing import Dict, List, Optional


def generate_html_report(
    title: str,
    sections: str,
    theme: Optional[Dict[str, str]] = None,
) -> str:
    """Generate a self-contained HTML report.

    Args:
        title:    Page title.
        sections: Markdown content string (processed inline into HTML tables).
        theme:    Optional CSS overrides.

    Returns:
        Complete HTML document as string.
    """
    styles = _default_styles()
    if theme:
        styles.update(theme)

    body = _markdown_to_html_blocks(sections)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{html_mod.escape(title)}</title>
<style>
{_css(styles)}
</style>
</head>
<body>
<div class="container">
<header>
<h1>{html_mod.escape(title)}</h1>
</header>
<main>
{body}
</main>
<footer>
<p>Generated by Kairos research reporting framework</p>
</footer>
</div>
</body>
</html>"""


def _default_styles() -> Dict[str, str]:
    return {
        "bg": "#ffffff",
        "text": "#1a1a2e",
        "accent": "#4361ee",
        "border": "#e0e0e0",
        "header-bg": "#f8f9fa",
        "font-family": "'Segoe UI', system-ui, -apple-system, sans-serif",
    }


def _css(colors: Dict[str, str]) -> str:
    return f"""
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ background: {colors["bg"]}; color: {colors["text"]}; font-family: {colors["font-family"]}; line-height: 1.6; padding: 2rem; }}
.container {{ max-width: 960px; margin: 0 auto; }}
header {{ border-bottom: 3px solid {colors["accent"]}; padding-bottom: 0.75rem; margin-bottom: 2rem; }}
h1 {{ font-size: 1.8rem; color: {colors["accent"]}; }}
h2 {{ font-size: 1.4rem; margin: 1.5rem 0 0.75rem; color: {colors["text"]}; }}
h3 {{ font-size: 1.15rem; margin: 1.25rem 0 0.5rem; }}
table {{ border-collapse: collapse; width: 100%; margin: 0.75rem 0 1.25rem; font-size: 0.9rem; }}
th, td {{ border: 1px solid {colors["border"]}; padding: 0.4rem 0.6rem; text-align: left; }}
th {{ background: {colors["header-bg"]}; font-weight: 600; }}
tr:nth-child(even) {{ background: {colors["header-bg"]}; }}
tr:hover {{ background: #eef1ff; }}
footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid {colors["border"]}; font-size: 0.85rem; color: #666; }}
code {{ background: #f0f0f0; padding: 0.1rem 0.3rem; border-radius: 3px; font-size: 0.85rem; }}
pre {{ background: #f5f5f5; padding: 1rem; border-radius: 4px; overflow-x: auto; }}
blockquote {{ border-left: 4px solid {colors["accent"]}; padding-left: 1rem; margin: 1rem 0; color: #555; }}
"""


def _markdown_to_html_blocks(md: str) -> str:
    """Minimal markdown-to-HTML for tables, bold, italic, code, links."""
    html_parts: List[str] = []
    in_table = False
    table_rows: List[str] = []

    for line in md.splitlines():
        stripped = line.strip()

        # Tables
        if stripped.startswith("|") and stripped.endswith("|"):
            if not in_table:
                in_table = True
                table_rows = []
            # Skip separator lines
            if (
                set(stripped.replace("|", "").replace("-", "").replace(":", "").strip())
                == set()
            ):
                continue
            cells = [c.strip() for c in stripped.strip("|").split("|")]
            # Also check for the actual header row detection: if this is the first row after separator, it's data
            tag = "th" if in_table and len(table_rows) == 0 else "td"
            row_html = f"<tr>{''.join(f'<{tag}>{_inline_html(c)}</{tag}>' for c in cells)}</tr>"
            table_rows.append(row_html)
            continue
        else:
            if in_table:
                html_parts.append(_render_table(table_rows, tag_body="td"))
                in_table = False
                table_rows = []

        # Empty line
        if not stripped:
            html_parts.append("")
            continue

        # Headings
        if stripped.startswith("### "):
            html_parts.append(f"<h3>{_inline_html(stripped[4:])}</h3>")
        elif stripped.startswith("## "):
            html_parts.append(f"<h2>{_inline_html(stripped[3:])}</h2>")
        elif stripped.startswith("# "):
            html_parts.append(f"<h1>{_inline_html(stripped[2:])}</h1>")

        # Horizontal rule
        elif stripped == "---":
            html_parts.append("<hr>")

        # Bold items (list-like)
        elif stripped.startswith("**") and stripped.endswith("**"):
            html_parts.append(
                f"<p><strong>{_inline_html(stripped.strip('*'))}</strong></p>"
            )

        # Unordered list items
        elif stripped.startswith("- "):
            html_parts.append(f"<li>{_inline_html(stripped[2:])}</li>")

        # Blockquote
        elif stripped.startswith("> "):
            html_parts.append(f"<blockquote>{_inline_html(stripped[2:])}</blockquote>")

        # Regular paragraph
        else:
            html_parts.append(f"<p>{_inline_html(stripped)}</p>")

    if in_table:
        html_parts.append(_render_table(table_rows, tag_body="td"))

    return "\n".join(html_parts)


def _render_table(rows: List[str], tag_body: str = "td") -> str:
    if not rows:
        return ""
    # First row is header
    header = rows[0].replace("<td>", "<th>").replace("</td>", "</th>")
    body = "\n".join(rows[1:])
    return f"<table><thead>{header}</thead><tbody>{body}</tbody></table>"


def _inline_html(text: str) -> str:
    escaped = html_mod.escape(text)
    escaped = escaped.replace("**", "<strong>", 1).replace("**", "</strong>", 1)
    escaped = escaped.replace("*", "<em>", 1).replace("*", "</em>", 1)
    escaped = escaped.replace("`", "<code>", 1).replace("`", "</code>", 1)
    return escaped
