from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Sequence

from intelligence.ablation.comparison import AblationComparison
from intelligence.benchmarks.benchmark_result import BenchmarkResult
from intelligence.experiments.registry import ExperimentRegistry
from intelligence.reporting.html_report import generate_html_report
from intelligence.reporting.leaderboard import rank_experiments
from intelligence.reporting.markdown_report import (
    generate_markdown_ablation_report,
    generate_markdown_benchmark_report,
    generate_markdown_leaderboard_report,
    generate_markdown_statistical_report,
)
from intelligence.reporting.reproducibility import (
    generate_benchmark_manifest,
    generate_experiment_manifest,
    generate_environment_snapshot,
)


def generate_full_report(
    output_dir: str | Path = "reports",
    title: str = "Kairos Research Report",
    benchmark_results: Optional[Sequence[BenchmarkResult]] = None,
    ablation_comparisons: Optional[Sequence[AblationComparison]] = None,
    experiment_registry: Optional[ExperimentRegistry] = None,
    formats: Optional[List[str]] = None,
) -> Dict[str, str]:
    """Generate a complete research report covering all available data.

    Args:
        output_dir:          Directory to write report files.
        title:               Report title.
        benchmark_results:   Optional benchmark results to include.
        ablation_comparisons: Optional ablation comparisons to include.
        experiment_registry: Optional registry for leaderboard + manifests.
        formats:             Output formats (``"md"``, ``"html"``, ``"json"``).
                             Defaults to ``["md", "html", "json"]``.

    Returns:
        Dict mapping format names to file paths of generated reports.
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    if formats is None:
        formats = ["md", "html", "json"]

    generated: Dict[str, str] = {}
    sections: List[str] = []
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # -- Collect data for manifests --
    manifest_data: Dict[str, object] = {
        "title": title,
        "generated_at": timestamp,
    }

    # -- Benchmark section --
    if benchmark_results:
        bm_md = generate_markdown_benchmark_report(
            list(benchmark_results), title=f"Benchmark Evaluation",
        )
        sections.append(bm_md)

        manifest_data["benchmark_datasets"] = [
            r.dataset_name for r in benchmark_results
        ]
        manifest_data["benchmark_query_count"] = sum(
            r.query_count for r in benchmark_results
        )

    # -- Ablation section --
    if ablation_comparisons:
        abl_md = generate_markdown_ablation_report(
            list(ablation_comparisons), title="Ablation Study",
        )
        sections.append(abl_md)

        manifest_data["ablation_comparisons"] = len(ablation_comparisons)

    # -- Statistical validation --
    stats_sections: List[str] = []
    if benchmark_results:
        for br in benchmark_results:
            if br.validation is not None:
                stats_md = generate_markdown_statistical_report(
                    br.validation, title=f"Validation: {br.dataset_name}",
                )
                stats_sections.append(stats_md)

    if ablation_comparisons:
        for ac in ablation_comparisons:
            if ac.validation is not None:
                stats_md = generate_markdown_statistical_report(
                    ac.validation,
                    title=f"Validation: {ac.treatment_label} vs {ac.baseline_label}",
                )
                stats_sections.append(stats_md)

    if stats_sections:
        sections.append("## Statistical Validation\n")
        sections.extend(stats_sections)

    # -- Leaderboard --
    if experiment_registry:
        runs = experiment_registry.list_runs()
        if runs:
            leaderboard = rank_experiments(runs)
            lb_md = generate_markdown_leaderboard_report(
                leaderboard, title="Experiment Leaderboard",
            )
            sections.append(lb_md)
            manifest_data["experiment_runs"] = len(runs)

    # -- Assemble full markdown --
    full_md = "\n\n".join([
        f"# {title}",
        "",
        f"**Generated:** {timestamp}",
        "",
        "## Table of Contents",
        "",
    ] + _build_toc(sections) + [
        "",
        "---",
        "",
    ] + sections + [
        "---",
        "",
        "*Report generated by Kairos research reporting framework*",
        "",
    ])

    if "md" in formats:
        md_path = out / "research_report.md"
        md_path.write_text(full_md, encoding="utf-8")
        generated["md"] = str(md_path)

    if "html" in formats:
        html_path = out / "research_report.html"
        html_content = generate_html_report(
            title=title,
            sections=full_md,
        )
        html_path.write_text(html_content, encoding="utf-8")
        generated["html"] = str(html_path)

    if "json" in formats:
        import json
        json_path = out / "research_report_summary.json"
        # Build a structured summary
        summary: Dict[str, object] = {
            "title": title,
            "generated_at": timestamp,
            "sections": [],
        }
        if benchmark_results:
            summary["sections"].append({
                "type": "benchmark",
                "datasets": [
                    {
                        "name": r.dataset_name,
                        "query_count": r.query_count,
                        "avg_recall": r.average_recall,
                        "avg_precision": r.average_precision,
                        "avg_latency_ms": r.average_latency_ms,
                        "success_rate": r.success_rate,
                        "fallback_rate": r.fallback_rate,
                    }
                    for r in benchmark_results
                ],
            })
        if ablation_comparisons:
            summary["sections"].append({
                "type": "ablation",
                "comparisons": len(ablation_comparisons),
            })
        json_path.write_text(json.dumps(summary, indent=2, default=str), encoding="utf-8")
        generated["json"] = str(json_path)

    # -- Reproducibility manifests --
    if experiment_registry:
        exp_manifest_path = generate_experiment_manifest(
            registry=experiment_registry,
            output_dir=out,
        )
        if exp_manifest_path:
            generated["experiment_manifest"] = str(exp_manifest_path)

    if benchmark_results:
        bm_manifest_path = generate_benchmark_manifest(
            benchmark_results=list(benchmark_results),
            output_dir=out,
        )
        if bm_manifest_path:
            generated["benchmark_manifest"] = str(bm_manifest_path)

    env_path = generate_environment_snapshot(output_dir=out)
    if env_path:
        generated["environment_snapshot"] = str(env_path)

    return generated


def _build_toc(sections: List[str]) -> List[str]:
    lines: List[str] = []
    for sec in sections:
        for line in sec.splitlines():
            if line.startswith("## "):
                heading = line.strip("# ")
                anchor = heading.lower().replace(" ", "-").replace(":", "")
                lines.append(f"- [{heading}](#{anchor})")
    return lines
