import type { Prisma } from "@prisma/client";
import {
  assertPublicHost,
  decodeEntities,
  defaultHttpGet,
  defaultResolveHost,
  loadTarget,
  readBoundedText,
  UrlSourceError,
  urlDocumentFileHash,
  type HttpGetFn,
  type HttpGetResult,
  type ResolveHostFn,
} from "@/lib/ingestion/url";

const YOUTUBE_MAX_BODY_BYTES = 5 * 1024 * 1024;
const YOUTUBE_FETCH_TIMEOUT_MS = 15_000;
const MAX_REDIRECTS = 5;
const YOUTUBE_MIN_CONTENT_CHARS = 20;
const WORDS_PER_PARAGRAPH = 40;
const USER_AGENT = "KairosYT/1.0 (+https://kairos.dev; transcript ingestion bot)";
const VIDEO_ID_RE = /^[A-Za-z0-9_-]{11}$/;
const SENTENCE_END_RE = /[.!?…]$/;

const YOUTUBE_HOSTS = new Set(["youtube.com", "youtu.be"]);

export type YouTubeTranscriptErrorCode =
  | "invalid_url"
  | "unsupported_host"
  | "invalid_video_id"
  | "transcript_unavailable"
  | "transcript_fetch"
  | "transcript_timeout"
  | "transcript_malformed"
  | "transcript_empty"
  | "too_many_redirects"
  | "too_large";

export class YouTubeTranscriptError extends Error {
  constructor(
    public readonly code: YouTubeTranscriptErrorCode,
    message: string,
    options?: { cause?: unknown },
  ) {
    super(message, options);
    this.name = "YouTubeTranscriptError";
  }
}

export interface YouTubeTranscript {
  videoId: string;
  canonicalUrl: string;
  title: string;
  languageCode: string | null;
  autoGenerated: boolean;
  cueCount: number;
  text: string;
}

export interface FetchYoutubeOptions {
  resolveHost?: ResolveHostFn;
  httpGet?: HttpGetFn;
  timeoutMs?: number;
  maxResponseBytes?: number;
  maxRedirects?: number;
}

export function parseYouTubeUrl(rawUrl: string): { videoId: string; canonicalUrl: string } {
  let url: URL;
  try {
    url = new URL(rawUrl.trim());
  } catch {
    throw new YouTubeTranscriptError("invalid_url", "YouTube URL could not be parsed");
  }
  if (url.protocol !== "http:" && url.protocol !== "https:") {
    throw new YouTubeTranscriptError("invalid_url", `Unsupported protocol: ${url.protocol}`);
  }

  // Host allowlist comes first: "youtube.com@evil.com" is an evil.com link,
  // not a credentials bug.
  const baseHost = stripHostPrefix(url.hostname.toLowerCase());
  if (!YOUTUBE_HOSTS.has(baseHost)) {
    throw new YouTubeTranscriptError("unsupported_host", `Not a YouTube host: ${url.hostname}`);
  }

  if (url.username || url.password) {
    throw new YouTubeTranscriptError("invalid_url", "URLs with embedded credentials are not allowed");
  }

  let videoId: string | null = null;
  if (baseHost === "youtu.be") {
    videoId = url.pathname.split("/")[1] ?? null;
  } else if (url.searchParams.get("v")) {
    videoId = url.searchParams.get("v");
  } else {
    const segment = url.pathname.split("/")[2] ?? null;
    if (url.pathname.startsWith("/shorts/") || url.pathname.startsWith("/embed/")) videoId = segment;
  }

  if (!videoId || !VIDEO_ID_RE.test(videoId)) {
    throw new YouTubeTranscriptError("invalid_video_id", "YouTube link has no valid video ID");
  }
  return { videoId, canonicalUrl: `https://www.youtube.com/watch?v=${videoId}` };
}

function stripHostPrefix(hostname: string): string {
  return hostname.replace(/^www\./i, "").replace(/^m\./i, "");
}

function isYoutubeHost(hostname: string): boolean {
  return YOUTUBE_HOSTS.has(stripHostPrefix(hostname.toLowerCase()));
}

function isRedirectStatus(status: number): boolean {
  return status === 301 || status === 302 || status === 303 || status === 307 || status === 308;
}

function mapUrlError(err: unknown): YouTubeTranscriptError {
  if (err instanceof YouTubeTranscriptError) return err;
  if (err instanceof UrlSourceError) {
    switch (err.code) {
      case "too_large":
        return new YouTubeTranscriptError("too_large", err.message, { cause: err });
      case "timeout":
        return new YouTubeTranscriptError("transcript_timeout", err.message, { cause: err });
      case "too_many_redirects":
        return new YouTubeTranscriptError("too_many_redirects", err.message, { cause: err });
      case "blocked":
        return new YouTubeTranscriptError("transcript_fetch", err.message, { cause: err });
      case "invalid_url":
        return new YouTubeTranscriptError("transcript_malformed", err.message, { cause: err });
      default:
        return new YouTubeTranscriptError("transcript_fetch", err.message, { cause: err });
    }
  }
  return new YouTubeTranscriptError(
    "transcript_fetch",
    err instanceof Error ? err.message : String(err),
    { cause: err },
  );
}

// Fixed, allowlisted endpoint host only. No generic fetch-any-URL path for
// YouTube; every hop is host-allowlisted AND resolves to a public address.
async function fetchYoutubeText(url: string, opts: Required<FetchYoutubeOptions>): Promise<string> {
  let current = loadTarget(url);
  for (let hop = 0; ; hop++) {
    if (!isYoutubeHost(current.hostname)) {
      throw new YouTubeTranscriptError("unsupported_host", `Redirect to non-YouTube host: ${current.hostname}`);
    }
    await assertPublicHost(current.hostname, opts.resolveHost);

    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), opts.timeoutMs);
    let response: HttpGetResult;
    try {
      response = await opts.httpGet(current.href, {
        signal: controller.signal,
        headers: {
          "user-agent": USER_AGENT,
          accept: "text/xml,application/x-www-form-urlencoded,*/*;q=0.1",
          "accept-language": "en",
        },
      });
    } catch (err) {
      if (err instanceof Error && err.name === "AbortError") {
        throw new YouTubeTranscriptError("transcript_timeout", `Request timed out after ${opts.timeoutMs}ms`, { cause: err });
      }
      throw new YouTubeTranscriptError("transcript_fetch", `Network error while fetching ${current.href}`, { cause: err });
    } finally {
      clearTimeout(timer);
    }

    if (isRedirectStatus(response.status)) {
      if (hop >= opts.maxRedirects) {
        throw new YouTubeTranscriptError("too_many_redirects", `More than ${opts.maxRedirects} redirects`);
      }
      const location = response.headers.get("location");
      if (!location) {
        throw new YouTubeTranscriptError("transcript_fetch", "Redirect response had no Location header");
      }
      try {
        current = loadTarget(new URL(location, current).href);
      } catch (err) {
        throw mapUrlError(err);
      }
      continue;
    }

    if (response.status !== 200) {
      throw new YouTubeTranscriptError("transcript_fetch", `HTTP ${response.status}`);
    }

    try {
      return await readBoundedText(response.body, opts.maxResponseBytes);
    } catch (err) {
      throw mapUrlError(err);
    }
  }
}

interface CaptionTrack {
  baseUrl?: string;
  languageCode?: string;
  kind?: string;
  name?: { simpleText?: string };
}

interface PlayerResponseLike {
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: CaptionTrack[];
    };
  };
  videoDetails?: {
    videoId?: string;
    title?: string;
  };
}

function extractPlayerResponse(infoBody: string): PlayerResponseLike {
  const params = new URLSearchParams(infoBody);
  if (params.get("status") === "fail") {
    throw new YouTubeTranscriptError("transcript_unavailable", "video info returned status=fail");
  }
  const encoded = params.get("player_response");
  if (!encoded) {
    throw new YouTubeTranscriptError("transcript_unavailable", "no player_response in video info");
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(encoded);
  } catch (err) {
    throw new YouTubeTranscriptError("transcript_malformed", "player_response was not valid JSON", { cause: err });
  }
  return parsed as PlayerResponseLike;
}

function selectCaptionTrack(player: PlayerResponseLike): CaptionTrack {
  const tracks = player.captions?.playerCaptionsTracklistRenderer?.captionTracks;
  if (!tracks || tracks.length === 0) {
    throw new YouTubeTranscriptError("transcript_unavailable", "no caption tracks available");
  }
  // Manual (kind !== "asr") is preferred over auto-generated; within the chosen
  // pool, an English track wins; otherwise the first usable track is used.
  const manual = tracks.filter((t) => !t.kind || t.kind !== "asr");
  const pool = manual.length > 0 ? manual : tracks;
  const english = pool.find((t) => (t.languageCode || "").toLowerCase().startsWith("en"));
  const track = english ?? pool[0];
  if (!track?.baseUrl) {
    throw new YouTubeTranscriptError("transcript_unavailable", "selected caption track had no baseUrl");
  }
  return track;
}

interface CaptionCue {
  start: number;
  duration: number;
  text: string;
}

function parseTimedText(body: string): CaptionCue[] {
  // A page body (or JSON blob) is not caption XML even if it contains <text>.
  if (!/<text\b/i.test(body) && !/<transcript\b/i.test(body)) {
    throw new YouTubeTranscriptError("transcript_malformed", "timedtext response is not caption XML");
  }
  const cues: CaptionCue[] = [];
  for (const match of body.matchAll(/<text\b([^>]*)>([\s\S]*?)<\/text>/gi)) {
    const attrs = match[1] ?? "";
    const start = parseFloat(/start="([^"]*)"/i.exec(attrs)?.[1] ?? "");
    const duration = parseFloat(/dur="([^"]*)"/i.exec(attrs)?.[1] ?? "0");
    const text = normalizeCueText(match[2] ?? "");
    if (!text) continue;
    cues.push({
      start: Number.isFinite(start) ? start : 0,
      duration: Number.isFinite(duration) ? duration : 0,
      text,
    });
  }
  return cues;
}

function normalizeCueText(raw: string): string {
  const plain = raw.replace(/<[^>]+>/g, "");
  return decodeEntities(plain).replace(/\s+/g, " ").trim();
}

function buildTranscriptText(cues: CaptionCue[]): string {
  const paragraphs: string[] = [];
  let words: string[] = [];
  let count = 0;
  const flush = () => {
    if (words.length > 0) {
      paragraphs.push(words.join(" "));
      words = [];
      count = 0;
    }
  };
  for (const cue of cues) {
    for (const word of cue.text.split(" ")) {
      words.push(word);
      count++;
      if (count >= WORDS_PER_PARAGRAPH || SENTENCE_END_RE.test(word)) flush();
    }
  }
  flush();
  return paragraphs.join("\n\n");
}

export async function fetchYouTubeTranscript(rawUrl: string, opts: FetchYoutubeOptions = {}): Promise<YouTubeTranscript> {
  const { videoId } = parseYouTubeUrl(rawUrl);
  const fullOpts: Required<FetchYoutubeOptions> = {
    resolveHost: opts.resolveHost ?? defaultResolveHost,
    httpGet: opts.httpGet ?? defaultHttpGet,
    timeoutMs: opts.timeoutMs ?? YOUTUBE_FETCH_TIMEOUT_MS,
    maxResponseBytes: opts.maxResponseBytes ?? YOUTUBE_MAX_BODY_BYTES,
    maxRedirects: opts.maxRedirects ?? MAX_REDIRECTS,
  };

  const infoUrl = `https://www.youtube.com/get_video_info?video_id=${videoId}&hl=en&el=embedded`;
  const player = extractPlayerResponse(await fetchYoutubeText(infoUrl, fullOpts));
  const track = selectCaptionTrack(player);

  const baseUrl = track.baseUrl;
  if (!baseUrl) {
    throw new YouTubeTranscriptError("transcript_unavailable", "selected caption track had no baseUrl");
  }

  let timedTextUrl: string;
  try {
    timedTextUrl = new URL(baseUrl, "https://www.youtube.com").href;
  } catch (err) {
    throw new YouTubeTranscriptError("transcript_malformed", "caption track baseUrl was invalid", { cause: err });
  }
  const timedTextBody = await fetchYoutubeText(timedTextUrl, fullOpts);

  const cues = parseTimedText(timedTextBody);
  if (cues.length === 0) {
    throw new YouTubeTranscriptError("transcript_empty", "timedtext contained no cues");
  }
  const text = buildTranscriptText(cues);
  if (text.trim().length < YOUTUBE_MIN_CONTENT_CHARS) {
    throw new YouTubeTranscriptError("transcript_empty", "transcribed text is too short to ingest");
  }

  return {
    videoId,
    canonicalUrl: `https://www.youtube.com/watch?v=${videoId}`,
    title: player.videoDetails?.title?.trim() || "",
    languageCode: track.languageCode || null,
    autoGenerated: track.kind === "asr",
    cueCount: cues.length,
    text,
  };
}

export function buildYouTubeDocumentData(params: {
  kbId: string;
  userId: string;
  sourceUrl: string;
  videoId: string;
  title: string;
  languageCode: string | null;
  autoGenerated: boolean;
  cueCount: number;
  text: string;
}): Prisma.DocumentUncheckedCreateInput {
  const buffer = Buffer.from(params.text, "utf8");
  const name = (params.title || `YouTube ${params.videoId}`).slice(0, 255);
  return {
    name,
    fileType: "txt",
    size: buffer.byteLength,
    fileHash: urlDocumentFileHash(params.text),
    sourceType: "YOUTUBE",
    sourceUrl: params.sourceUrl,
    status: "STORED",
    storageProvider: null,
    storageKey: null,
    storageUrl: null,
    knowledgeBaseId: params.kbId,
    uploadedById: params.userId,
    metadata: {
      mimeType: "text/plain",
      source: "youtube",
      videoId: params.videoId,
      title: params.title,
      languageCode: params.languageCode,
      autoGenerated: params.autoGenerated,
      cueCount: params.cueCount,
    },
  };
}